#!/bin/bash

# Get bendit
# by using git instead of curl to get release bundle, if they
# update repo, I'll get latest upon a new rebuild even if
# there isn't an new release made
git clone https://github.com/r78v10a07/bendit.git

#For release archive (unlike goghugo releases) could have used following
# based on https://stackoverflow.com/a/23164066/8508004 . The trick is 
# need to add `-s` option to curl!!! To handle certificates I think
# curl -sL -o thedl.tar.gz https://github.com/r78v10a07/bendit/archive/1.0.tar.gz
# tar xzf thedl.tar.gz 
# -OR COULD JUST DO download and tar in one step using pipe.
# curl -sL https://github.com/r78v10a07/bendit/archive/1.0.tar.gz | xz
# HOWEVER, USING GIT TO STICK TO THE REPO SO ID UPDATED WITHOUT A RELEASE
# I HAVE LATEST. Plus don't need to determine the version using git in the master branc.

# Compile bendit
cd bendit
make


# Add bendIt to the path
mkdir -p ~/.local/bin
# to create alias for bendIt ("~/.local/bin" is in the PATH)
cd ~/.local/bin
ln -s ~/bendit/bin/bendIt bendIt


# Upon addition of Jupytext, I was seeing it want to build when session launched. Seems
# explained at https://jupytext.readthedocs.io/en/latest/install.html#jupytext-commands-in-jupyterlab
# >"The Jupytext extension for JupyterLab is bundled with Jupytext. Installing Jupytext will trigger a build of JupyterLab the next time you open it. If you prefer, you can trigger the build manually with `jupyter lab build`"
# Trying that here to avoid it later showing pop-up about it.
jupyter lab build
